"""Build a markdown leaderboard table from external result files.

Reads ``*.json`` files from a directory, validates them against the
:class:`ExternalResult` schema, extracts per-category metrics, and
produces a sorted Markdown table.

Sorting: **worst (highest) risk score first** — the most leaky systems
appear at the top so reviewers spot problems immediately.

Invalid files are silently skipped (with a warning printed to stderr).
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path

from ragleaklab.bench.external import ExternalResult

__all__ = [
    "TableRow",
    "build_table_rows",
    "render_table_md",
]

# ── Category → column mapping ───────────────────────────────────────

_CATEGORY_TO_COLUMN: dict[str, str] = {
    "canary": "canary",
    "semantic": "semantic",
    "poisoning": "poisoning",
    "crossdoc": "acl",
}


@dataclass
class TableRow:
    """One row of the leaderboard table."""

    system_name: str
    system_type: str
    bundle_version: str
    risk_score: float
    canary_leak_rate: float | None = None
    semantic_leak_rate: float | None = None
    poisoning_indicator_rate: float | None = None
    acl_breach_rate: float | None = None
    notes: str = ""
    source_file: str = ""


# ── Builder ──────────────────────────────────────────────────────────


def _extract_category_rate(
    result: ExternalResult,
    category: str,
) -> float | None:
    """Return the average fail_rate for packs in a given category.

    Returns None when no packs match the category.
    """
    packs = [p for p in result.results_summary.pack_results if p.category == category]
    if not packs:
        return None
    return sum(p.fail_rate for p in packs) / len(packs)


def build_table_rows(
    input_dir: Path,
    *,
    quiet: bool = False,
) -> list[TableRow]:
    """Parse all ``*.json`` files in *input_dir* and return table rows.

    Invalid files are skipped.  Rows are sorted by risk score descending
    (worst first), with ties broken by system name for stability.
    """
    rows: list[TableRow] = []

    json_files = sorted(input_dir.glob("*.json"))
    for path in json_files:
        try:
            with open(path) as f:
                data = json.load(f)
            result = ExternalResult.model_validate(data)
        except Exception as exc:
            if not quiet:
                print(f"⚠ Skipping {path.name}: {exc}", file=sys.stderr)
            continue

        rows.append(
            TableRow(
                system_name=result.system_name,
                system_type=result.system_type,
                bundle_version=result.bundle.version,
                risk_score=result.results_summary.risk_score,
                canary_leak_rate=_extract_category_rate(result, "canary"),
                semantic_leak_rate=_extract_category_rate(result, "semantic"),
                poisoning_indicator_rate=_extract_category_rate(result, "poisoning"),
                acl_breach_rate=_extract_category_rate(result, "crossdoc"),
                notes=result.notes.replace("\n", " ").strip()[:120],
                source_file=path.name,
            )
        )

    # Sort: worst first (highest risk score), then by name for stability
    rows.sort(key=lambda r: (-r.risk_score, r.system_name))
    return rows


# ── Renderer ─────────────────────────────────────────────────────────


def _fmt_rate(rate: float | None) -> str:
    """Format a 0-1 rate as a percentage, or ``—`` when absent."""
    if rate is None:
        return "—"
    return f"{rate * 100:.1f}%"


def _fmt_risk(score: float) -> str:
    return f"{score:.4f}"


def _truncate(text: str, max_len: int = 60) -> str:
    if len(text) <= max_len:
        return text
    return text[: max_len - 1] + "…"


def render_table_md(rows: list[TableRow]) -> str:
    """Render rows into a Markdown table with header and auto-generation notice."""
    lines: list[str] = []

    lines.append("<!-- AUTO-GENERATED by `ragleaklab results build-table` — do not edit -->")
    lines.append("")
    lines.append("# RAGLeakLab External Results Leaderboard")
    lines.append("")
    lines.append(
        "Sorted by overall risk score (highest risk first).  "
        "See [README.md](README.md) for how to contribute."
    )
    lines.append("")

    # Header
    header = (
        "| System | Type | Bundle | Risk Score "
        "| Canary Leaks | Semantic Leakage | Poisoning Indicators "
        "| ACL Breaches | Notes |"
    )
    sep = "|--------|------|--------|" + ":---:|" * 5 + "------|"
    lines.append(header)
    lines.append(sep)

    if not rows:
        lines.append("| *(no results yet)* | | | | | | | | |")
    else:
        for row in rows:
            cols = [
                f"**{row.system_name}**",
                row.system_type,
                f"`{row.bundle_version}`",
                _fmt_risk(row.risk_score),
                _fmt_rate(row.canary_leak_rate),
                _fmt_rate(row.semantic_leak_rate),
                _fmt_rate(row.poisoning_indicator_rate),
                _fmt_rate(row.acl_breach_rate),
                _truncate(row.notes),
            ]
            lines.append("| " + " | ".join(cols) + " |")

    lines.append("")
    lines.append(f"*{len(rows)} system(s) tested.*")
    lines.append("")
    return "\n".join(lines)
