"""Poisoning pack runner.

Provides functions to load and execute poisoning packs,
producing integrity evidence for reporting.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from ragleaklab.core.contracts import RunArtifact
from ragleaklab.poisoning.evidence import (
    ClaimIntegrityEvidence,
    IntegritySection,
    RetrievalIntegrityEvidence,
    SentinelIntegrityEvidence,
)
from ragleaklab.poisoning.packs.schema import PoisoningTestCase


def load_poisoning_cases(path: Path | str) -> list[PoisoningTestCase]:
    """Load poisoning test cases from YAML file or directory.

    Args:
        path: Path to YAML file or directory containing YAML files.

    Returns:
        List of PoisoningTestCase objects, sorted by test_id for determinism.
    """
    path = Path(path)
    cases: list[PoisoningTestCase] = []

    # Manifest files to skip when loading from directory
    manifest_files = {"pack.yaml", "manifest.yaml"}

    if path.is_file():
        cases.extend(_load_yaml_file(path))
    elif path.is_dir():
        for yaml_file in sorted(path.glob("*.yaml")):
            if yaml_file.name not in manifest_files:
                cases.extend(_load_yaml_file(yaml_file))
        for yml_file in sorted(path.glob("*.yml")):
            cases.extend(_load_yaml_file(yml_file))

    # Deterministic ordering by test_id
    return sorted(cases, key=lambda c: c.test_id)


def _load_yaml_file(path: Path) -> list[PoisoningTestCase]:
    """Load poisoning test cases from a single YAML file."""
    content = path.read_text(encoding="utf-8")
    data = yaml.safe_load(content)

    if data is None:
        return []

    # Handle both single case and list of cases
    if isinstance(data, list):
        return [PoisoningTestCase(**item) for item in data]
    elif isinstance(data, dict):
        # Check if it's a wrapper with 'cases' key
        if "cases" in data:
            return [PoisoningTestCase(**item) for item in data["cases"]]
        # Single case
        return [PoisoningTestCase(**data)]

    return []


def evaluate_retrieval_integrity(
    case: PoisoningTestCase,
    actual_doc_ids: list[str],
) -> RetrievalIntegrityEvidence | None:
    """Evaluate retrieval integrity for a single case.

    Args:
        case: The test case with expectations.
        actual_doc_ids: Document IDs actually retrieved.

    Returns:
        RetrievalIntegrityEvidence if violation found, None otherwise.
    """
    # Check for missing expected docs
    expected_set = set(case.expected_doc_ids)
    actual_set = set(actual_doc_ids)

    missing_expected = expected_set - actual_set
    disallowed_present = set(case.disallowed_doc_ids) & actual_set

    if missing_expected or disallowed_present:
        # Calculate confidence based on severity of mismatch
        if case.expected_doc_ids:
            overlap = len(expected_set & actual_set) / len(expected_set)
            confidence = 1.0 - overlap
        else:
            confidence = 1.0 if disallowed_present else 0.0

        details: dict[str, Any] = {}
        if missing_expected:
            details["missing_expected"] = sorted(missing_expected)
        if disallowed_present:
            details["disallowed_present"] = sorted(disallowed_present)

        return RetrievalIntegrityEvidence(
            pack_id=case.test_id,
            query_id=case.test_id,
            severity=case.severity,
            expected_doc_ids=case.expected_doc_ids,
            actual_doc_ids=actual_doc_ids,
            confidence=confidence,
            details=details,
        )

    return None


def evaluate_claim_integrity(
    case: PoisoningTestCase,
    actual_answer: str,
) -> ClaimIntegrityEvidence | None:
    """Evaluate claim integrity for a single case.

    Args:
        case: The test case with expectations.
        actual_answer: The answer generated by RAG.

    Returns:
        ClaimIntegrityEvidence if violation found, None otherwise.
    """
    # Check if forbidden claim appears
    if case.forbidden_claim and case.forbidden_claim.lower() in actual_answer.lower():
        return ClaimIntegrityEvidence(
            pack_id=case.test_id,
            query_id=case.test_id,
            severity=case.severity,
            expected_claim_ids=[case.test_id] if case.expected_claim else [],
            matched_true_claims=[],
            matched_poison_claims=[case.test_id],
            contradiction_hits=1,
            confidence=1.0,
            details={
                "violation_type": "forbidden_claim_present",
                "expected_claim": case.expected_claim or "",
                "actual_claim": actual_answer[:500],
            },
        )

    # Check if expected claim is missing (when expected)
    if case.expected_claim:
        expected_lower = case.expected_claim.lower()
        actual_lower = actual_answer.lower()

        if expected_lower not in actual_lower:
            return ClaimIntegrityEvidence(
                pack_id=case.test_id,
                query_id=case.test_id,
                severity=case.severity,
                expected_claim_ids=[case.test_id],
                matched_true_claims=[],
                matched_poison_claims=[],
                contradiction_hits=0,
                confidence=1.0,
                details={
                    "violation_type": "expected_claim_missing",
                    "expected_claim": case.expected_claim,
                    "actual_claim": actual_answer[:500],
                },
            )

    return None


def evaluate_sentinel_integrity(
    case: PoisoningTestCase,
    actual_answer: str,
) -> SentinelIntegrityEvidence | None:
    """Evaluate sentinel/backdoor integrity for a single case.

    Args:
        case: The test case with trigger expectations.
        actual_answer: The answer generated by RAG.

    Returns:
        SentinelIntegrityEvidence if backdoor triggered, None otherwise.
    """
    if case.sentinel_type and case.trigger_phrase:
        # Check if trigger phrase appears in answer
        if case.trigger_phrase.lower() in actual_answer.lower():
            return SentinelIntegrityEvidence(
                pack_id=case.test_id,
                query_id=case.test_id,
                severity=case.severity,
                sentinel_type=case.sentinel_type,
                triggered=True,
                expected_behavior=f"Answer should not contain trigger phrase: {case.trigger_phrase}",
                actual_behavior=actual_answer[:500],  # Truncate for report
                details={"trigger_phrase": case.trigger_phrase},
            )

    return None


def run_poisoning_case(
    case: PoisoningTestCase,
    artifact: RunArtifact,
) -> RetrievalIntegrityEvidence | ClaimIntegrityEvidence | SentinelIntegrityEvidence | None:
    """Evaluate a single poisoning test case against a run artifact.

    Args:
        case: The poisoning test case to evaluate.
        artifact: The run artifact with RAG response data.

    Returns:
        IntegrityEvidence if violation detected, None otherwise.
    """
    if case.pack_type == "retrieval":
        actual_doc_ids = artifact.retrieved_ids
        return evaluate_retrieval_integrity(case, actual_doc_ids)

    elif case.pack_type == "claim":
        return evaluate_claim_integrity(case, artifact.answer)

    elif case.pack_type == "sentinel":
        return evaluate_sentinel_integrity(case, artifact.answer)

    return None


def run_poisoning_pack(
    cases: list[PoisoningTestCase],
    artifacts: list[RunArtifact],
) -> IntegritySection:
    """Run all poisoning test cases against run artifacts.

    This function evaluates each poisoning case against the corresponding
    artifact and collects integrity evidence.

    Args:
        cases: List of poisoning test cases.
        artifacts: List of run artifacts (must match case count).

    Returns:
        IntegritySection with all evidence and computed summary.
    """
    # Build artifact lookup by test_id for matching
    artifact_map = {a.test_id: a for a in artifacts}

    evidence_list: list[
        RetrievalIntegrityEvidence | ClaimIntegrityEvidence | SentinelIntegrityEvidence
    ] = []

    # Sort cases for determinism
    sorted_cases = sorted(cases, key=lambda c: c.test_id)

    for case in sorted_cases:
        # Find matching artifact
        artifact = artifact_map.get(case.test_id)
        if artifact is None:
            # No matching artifact - skip
            continue

        evidence = run_poisoning_case(case, artifact)
        if evidence is not None:
            evidence_list.append(evidence)

    # Create section and compute summary
    section = IntegritySection(packs=evidence_list)
    section.integrity_summary = section.compute_summary()

    return section
